name: "Build Terraform Configs"
on:
  push:
    paths:
      - "**.tf"
  pull_request:
    paths:
      - "**.tf"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v3
      - name: Get the system requirements.
        run: sudo apt-get install graphviz webp -y
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform -chdir=Terraform/ init
      - name: Check if a .tf has been formatted correctly.
        run: terraform -chdir=Terraform/ fmt
      - name: Terraform Validate
        run: terraform -chdir=Terraform/ validate
      - name: Terraform Generate Graph
        run: terraform -chdir=Terraform/ graph | dot -Tpng -o assets/remove/terraform-graph.png
      - name: Convert the image to webp
        run: cwebp assets/remove/terraform-graph.png -o assets/remove/terraform-graph.webp
