name: Dart
on:
  push:
    paths:
      - "**.js"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v2
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
    - name: Run the code
      run: |
        ALL_FILES_IN_DIRECTORY=$(find Dart/ -type f -name "*.dart")
        for CURRENT_FILE_IN_DIRECTORY in ${ALL_FILES_IN_DIRECTORY}; do
          ALL_FILES_LIST[$ADD_CONTENT]=$CURRENT_FILE_IN_DIRECTORY
          ADD_CONTENT=$(("$ADD_CONTENT" + 1))
        done
        for FILE_LIST in "${ALL_FILES_LIST[@]}"; do
          echo ${FILE_LIST}
          dart ${FILE_LIST}
        done
