name: Go
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "Go/"
        type: ".go"
    - name: Run the Go/hello-world.go
      run: |
        for found_files in ${{ steps.pl.outputs.paths }}; do
          go run ${found_files}
        done
