name: JavaScript
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v2
    - name: Use Node.js v16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Run the javascript/array.js
      run: node javascript/array.js
