name: TypeScript
on:
  push:
    paths:
      - "**.ts"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Run the code
        run: |
          ALL_FILES_IN_DIRECTORY=$(find TypeScript/ -type f -name "*.ts")
          for CURRENT_FILE_IN_DIRECTORY in ${ALL_FILES_IN_DIRECTORY}; do
            ALL_FILES_LIST[${ADD_CONTENT}]=${CURRENT_FILE_IN_DIRECTORY}
            ADD_CONTENT=$(("${ADD_CONTENT}" + 1))
          done
          for FILE_LIST in "${ALL_FILES_LIST[@]}"; do
            npm install --global typescript
            tsc ${FILE_LIST}
            node ${FILE_LIST%.*}.js
          done
